import fetch from 'node-fetch';
import * as cheerio from 'cheerio';
import * as fs from 'fs';
import * as path from 'path';
import { TrendingRepo } from './types';
import { analyzeRepo } from './analyzer';
import { loadConfig } from './config';
import { loadHistory, saveHistory, addRecord } from './history';
import { updateCatalog } from './catalog';

const REPORTS_DIR = path.resolve(__dirname, '..', 'reports');

function ensureReportsDir() {
  if (!fs.existsSync(REPORTS_DIR)) fs.mkdirSync(REPORTS_DIR, { recursive: true });
}

function generateReport(repo: TrendingRepo, analysis: string, title: string): string {
  const date = new Date().toISOString().slice(0, 10);
  const safeTitle = title.replace(/[\\/:*?"<>|]/g, '').slice(0, 50);
  const repoSlug = repo.name.replace(/\//g, '-');
  const filename = `${safeTitle}-${repoSlug}.md`;

  const content = `# ${repo.name} - 指定仓库深度分析

> 📅 ${date} | ⭐ ${repo.stars} stars (+${repo.todayStars} today) | 🔧 ${repo.language || 'N/A'}
>
> 🔗 仓库地址: [${repo.url}](${repo.url})
> 📦 Git Clone: \\\`git clone https://github.com/${repo.name}.git\\\`
> 📖 README: [README.md](${repo.url}#readme)

${analysis}

---
*Generated by github-trending-analyzer (manual mode) | ${date}*
`;

  ensureReportsDir();
  const filepath = path.join(REPORTS_DIR, filename);
  fs.writeFileSync(filepath, content, 'utf-8');
  return filename;
}

function parseStarCount(text: string): number {
  if (!text) return 0;
  const cleaned = text.replace(/,/g, '').replace(/stars?/gi, '').trim();
  const num = parseFloat(cleaned);
  if (cleaned.toLowerCase().includes('k')) return Math.round(num * 1000);
  return Math.round(num) || 0;
}

async function fetchRepoInfoViaApi(owner: string, repo: string, token: string): Promise<TrendingRepo | null> {
  const apiUrl = `https://api.github.com/repos/${owner}/${repo}`;
  const res = await fetch(apiUrl, {
    headers: {
      'Authorization': `token ${token}`,
      'Accept': 'application/vnd.github.v3+json',
    },
  });
  if (!res.ok) return null;
  const data: any = await res.json();
  return {
    name: data.full_name,
    description: data.description || '',
    language: data.language || 'N/A',
    stars: data.stargazers_count ?? 0,
    todayStars: 0,
    url: data.html_url,
  };
}

async function fetchRepoInfoViaScrape(owner: string, repo: string): Promise<TrendingRepo> {
  const pageUrl = `https://github.com/${owner}/${repo}`;
  const html = await (await fetch(pageUrl)).text();
  const $ = cheerio.load(html);

  const description =
    $('meta[name="description"]').attr('content')?.trim() ||
    $('meta[property="og:description"]').attr('content')?.trim() ||
    $('p.f4.my-3').text().trim() ||
    '';

  const language = $('[itemprop="programmingLanguage"]').text().trim() || 'N/A';

  let stars = 0;
  const starText =
    $('#repo-stars-counter-star').attr('title') ||
    $('#repo-stars-counter-star').text().trim() ||
    $('a[href$="/stargazers"] .Counter').text().trim() ||
    $('span.Counter[href$="/stargazers"]').text().trim();
  if (starText) stars = parseStarCount(starText);

  return {
    name: `${owner}/${repo}`,
    description,
    language,
    stars,
    todayStars: 0,
    url: pageUrl,
  };
}

async function fetchRepoInfo(owner: string, repo: string, token?: string): Promise<TrendingRepo> {
  // 有 token → 优先 API，失败回退页面抓取
  if (token) {
    try {
      const result = await fetchRepoInfoViaApi(owner, repo, token);
      if (result) return result;
    } catch {
      // API 失败，静默回退
    }
  }

  return fetchRepoInfoViaScrape(owner, repo);
}

function parseRepo(input: string): { owner: string; repo: string } | null {
  // 支持格式: owner/repo 或 https://github.com/owner/repo
  const cleaned = input.replace(/^https?:\/\/github\.com\//i, '').replace(/\/$/, '').replace(/\.git$/, '');
  const parts = cleaned.split('/').filter(Boolean);
  if (parts.length !== 2) return null;
  return { owner: parts[0], repo: parts[1] };
}

async function main() {
  const arg = process.argv[2];
  if (!arg) {
    console.log('用法: npm run analyze <owner/repo | GitHub URL>');
    console.log('示例: npm run analyze "ruvnet/ruflo"');
    console.log('示例: npm run analyze "https://github.com/vercel/ai"');
    process.exit(1);
  }

  const parsed = parseRepo(arg);
  if (!parsed) {
    console.error('❌ 无效格式，请使用 owner/repo 或完整 GitHub URL');
    process.exit(1);
  }

  console.log(`🔍 指定仓库分析: ${parsed.owner}/${parsed.repo}\n`);

  const config = loadConfig();
  const token = config.githubToken || undefined;

  if (token) {
    console.log('🌐 通过 GitHub API 获取仓库信息...');
  } else {
    console.log('🌐 通过页面抓取获取仓库信息（配置 githubToken 可获完整元数据）...');
  }

  // 1. 获取仓库信息
  const repo = await fetchRepoInfo(parsed.owner, parsed.repo, token);
  console.log(`📦 ${repo.name} | 🔧 ${repo.language} | ⭐ ${repo.stars}\n`);

  // 2. 调用 AI 深度分析
  console.log('🤖 正在调用 AI 深度分析...');
  const { content: analysisContent, tags, summary, title } = await analyzeRepo(repo);
  console.log(`✅ 分析完成 | 标签: ${tags.join(', ')}`);
  console.log(`📝 摘要: ${summary}\n`);

  // 3. 生成报告
  const reportFile = generateReport(repo, analysisContent, title);
  console.log(`📄 报告已生成: reports/${reportFile}`);

  // 4. 更新历史
  const date = new Date().toISOString().slice(0, 10);
  const history = loadHistory();
  addRecord(history, {
    date,
    repo: repo.name,
    stars: repo.stars,
    language: repo.language,
    todayStars: repo.todayStars,
    reportFile: `reports/${reportFile}`,
    tags,
    summary,
  });
  saveHistory(history);

  // 5. 更新索引
  updateCatalog(history);
  console.log('📇 索引目录已更新');

  console.log('\n✅ 完成!');
}

main().catch(err => {
  console.error('Fatal error:', err);
  process.exit(1);
});