import * as fs from 'fs';
import * as path from 'path';
import { fetchTrending, pickTopNew } from './trending';
import { loadHistory, saveHistory, getExistingRepos, addRecord } from './history';
import { updateCatalog } from './catalog';
import { analyzeRepo } from './analyzer';

const REPORTS_DIR = path.resolve(__dirname, '..', 'reports');

function ensureReportsDir() {
  if (!fs.existsSync(REPORTS_DIR)) fs.mkdirSync(REPORTS_DIR, { recursive: true });
}

function generateReport(repo: ReturnType<typeof pickTopNew>, analysis: string): string {
  if (!repo) return '';
  const date = new Date().toISOString().slice(0, 10);
  const repoSlug = repo.name.replace(/\//g, '-');
  const filename = `${date}-${repoSlug}.md`;

  const content = `# ${repo.name} - GitHub Trending 深度分析

> 📅 ${date} | ⭐ ${repo.stars} stars (+${repo.todayStars} today) | 🔧 ${repo.language || 'N/A'}
>
> 🔗 仓库地址: [${repo.url}](${repo.url})
> 📦 Git Clone: \\\`git clone https://github.com/${repo.name}.git\\\`
> 📖 README: [README.md](${repo.url}#readme)

${analysis}

---
*Generated by github-trending-analyzer | ${date}*
`;

  ensureReportsDir();
  const filepath = path.join(REPORTS_DIR, filename);
  fs.writeFileSync(filepath, content, 'utf-8');
  return filename;
}

async function main() {
  console.log('🚀 GitHub Trending Daily Analyzer');
  console.log('='.repeat(40));

  // 1. 加载历史
  const history = loadHistory();
  const existing = getExistingRepos(history);
  console.log(`📋 历史记录: ${existing.length} 个项目`);

  // 2. 抓取 Trending
  console.log('🌐 正在抓取 GitHub Trending...');
  let repos;
  try {
    repos = await fetchTrending();
    console.log(`✅ 抓取到 ${repos.length} 个 trending 项目`);
  } catch (err: any) {
    console.error(`❌ 抓取失败: ${err.message}`);
    process.exit(1);
  }

  // 3. 去重选第一个新项目
  const repo = pickTopNew(repos, existing);
  if (!repo) {
    console.log('⚠️ 今日所有 trending 项目均已分析过，跳过');
    return;
  }
  console.log(`📦 选中: ${repo.name} (${repo.language || 'N/A'}, ⭐${repo.stars}, +${repo.todayStars} today)`);

  // 4. Claude 深度分析
  console.log('🤖 正在调用 Claude 深度分析...');
  const { content: analysisContent, tags, summary } = await analyzeRepo(repo);
  console.log(`✅ 分析完成 | 标签: ${tags.join(', ')}`);
  console.log(`📝 摘要: ${summary}`);

  // 5. 生成报告
  const reportFile = generateReport(repo, analysisContent);
  console.log(`📄 报告已生成: reports/${reportFile}`);

  // 6. 更新历史
  const date = new Date().toISOString().slice(0, 10);
  addRecord(history, {
    date,
    repo: repo.name,
    stars: repo.stars,
    language: repo.language,
    todayStars: repo.todayStars,
    reportFile: `reports/${reportFile}`,
    tags,
    summary,
  });
  saveHistory(history);

  // 7. 更新索引目录
  updateCatalog(history);
  console.log('📇 索引目录已更新');

  console.log('='.repeat(40));
  console.log('✅ 完成!');
}

main().catch(err => {
  console.error('Fatal error:', err);
  process.exit(1);
});
